# Generated by Django 4.1.5 on 2023-02-01 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Users', models.CharField(max_length=100, verbose_name='User')),
                ('Passwords', models.CharField(max_length=100, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200, verbose_name='Name')),
                ('Number', models.IntegerField()),
                ('Email', models.CharField(max_length=500, verbose_name='Email')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.user')),
            ],
        ),
    ]
